services:
  frontend:
    networks:
      - app-network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  backend:
    networks:
      - app-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=${BACKEND_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_CONN_STRING=${MONGO_CONN_STRING}
      - GEMINI_KEY=${GEMINI_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      
networks:
  app-network:
    driver: bridge