services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_CONN_STRING=${MONGO_CONN_STRING}
      - GEMINI_KEY=${GEMINI_KEY}

      
